#!/usr/bin/env bash
# Regenerate the repo-root checksums.txt from the jars that are actually in build/libs.
#
# The root file used to claim it was "regenerated on every build" while being hand-run, so it
# went stale silently: after the bump to 1.1.1 every path in it named a 1.1.0 jar that no longer
# existed, and not one line resolved. A digest that hashes nothing is worse than no digest,
# because it reads as evidence. This script is what makes that first line true.
#
# It is NOT a release record — that is archived/v<version>/checksums.txt, generated from the
# archived jars themselves and never regenerated.
#
#   ./tools/regen-checksums.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

VERSION="$(sed -n 's/^mod_version=//p' neoforge/gradle.properties | tr -d '[:space:]')"
[ -n "$VERSION" ] || { echo "FATAL: could not read mod_version"; exit 1; }

MC="$(sed -n 's/^minecraft_version=//p' neoforge/gradle.properties | tr -d '[:space:]')"

paths=()
missing=()
for loader in neoforge fabric forge; do
  jar="$loader/build/libs/NexusCore-$loader-$VERSION-$MC.jar"
  if [ -f "$jar" ]; then paths+=("$jar"); else missing+=("$jar"); fi
done

if [ "${#missing[@]}" -ne 0 ]; then
  echo "FATAL: build outputs are missing — run ./gradlew build in each loader first:"
  printf '  %s\n' "${missing[@]}"
  exit 1
fi

{
  echo "# Current build outputs, regenerated by tools/regen-checksums.sh. NOT a release record."
  echo "# The immutable record of a published version is archived/v<version>/checksums.txt."
  echo "# Build: $VERSION (version, ADR-0012)"
  sha256sum "${paths[@]}"
} > checksums.txt

echo "checksums.txt regenerated for build $VERSION:"
sed -n '4,$p' checksums.txt | sed 's/^/  /'
